### ISSUE TITLE
Version docker images?

### ISSUE THREAD

**Issue by jperville** [PierreVincent/k8s-grafana-watcher#1]
Would it be possible to version the releases of this project and the associated images on docker hub?
It would make it easier to use those docker images without having to specify imagePullPolicy Always in the kubernetes template.

**Comment by PierreVincent** [comment]
Yes for sure, I'll create a release for the current one (which is pretty much the only one at the minute) and I'll make sure next releases get tagged correctly.

Thanks for the feedback!

**Comment by PierreVincent** [comment]
Done now - current version is tagged as `v0.1.0`.

**Comment by jperville** [comment]
Thank you very much!
