### ISSUE TITLE
Wait on grafana to be ready using /api/health endpoint

### ISSUE THREAD

**Issue by jperville** [PierreVincent/k8s-grafana-watcher#3]
Hi @PierreVincent ,

Since v4.3.0, Grafana has a `/api/health` endpoint.

Waiting for Grafana to be ready could be implemented by polling this endpoint rather than sleeping for 60 seconds and hoping for the best (see https://github.com/PierreVincent/k8s-grafana-watcher/blob/master/main.go#L71-L73).

**Comment by PierreVincent** [comment]
Yes, waiting on Health is 100% the way to go. I'll take a look at that soon 👍

**Comment by PierreVincent** [comment]
Done and released in `v0.2.0`
